apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dqiehtf5e-python 
  janus-idp.io/tekton: dqiehtf5e-python
  backstage.io/kubernetes-id: dqiehtf5e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dqiehtf5e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml